# @format

version: 2.0
parallelism: 3
jobs:
  unit_tests:
    working_directory: ~/huridocs/uwazi
    environment:
      CC_TEST_REPORTER_ID: 61434ccfc3eeb2ed7b9cfec1d61c4e0ca115a32c1eebfefe404d1ecb77d73358 #codelimate api key
    docker:
      - image: circleci/node:10.17.0-browsers
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
        environment:
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms750m -Xmx750m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v10-yarn-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v10-yarn-dependencies-

      - run: yarn install
      - run: sudo apt-get install poppler-utils
      - save_cache:
          paths:
            - ./node_modules
            - ~/.mongodb-binaries
          key: v10-yarn-dependencies-{{ checksum "package.json" }}

      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      # run tests!
      - run: wget --waitretry=5 --retry-connrefused -v http://127.0.0.1:9200/ #check if elastic is up
      - run: ./cc-test-reporter before-build #prepare codeclimate code coverage reporter
      - run: ./node_modules/.bin/jest --coverage --maxWorkers=2 #run tests
      - run: ./cc-test-reporter after-build --exit-code $? #send codecoverage
  eslint:
    working_directory: ~/huridocs/uwazi
    docker:
      - image: circleci/node:10.17.0-browsers
    steps:
      - checkout
      - run: yarn eslint
  e2e_tests:
    working_directory: ~/huridocs/uwazi
    docker:
      - image: circleci/node:10.17.0-browsers
      - image: circleci/mongo:4.0.3
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
        environment:
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms750m -Xmx750m

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v10-yarn-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v10-yarn-dependencies-

      - run: yarn install
      - run: sudo apt-get install mongodb-clients
      - run: sudo apt-get install poppler-utils
      - run: yarn production-build
      - save_cache:
          paths:
            - ./node_modules
            - ~/.mongodb-binaries
          key: v10-yarn-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn blank-state
      - run:
          command: yarn run-production
          background: true
      - run: sleep 15 && wget --waitretry=5 --retry-connrefused -v http://127.0.0.1:3000/ #check if server is up
      - run: yarn e2e
workflows:
  version: 2
  build:
    jobs:
      - "unit_tests"
      - "e2e_tests"
      - "eslint"
